services:
  db:
    image: postgres:17-alpine
    container_name: agromart-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: agromart
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: agromart-backend
    volumes:
      - ./.env:/app/.env
    environment:
      APP_ENV: development
      APP_DB_HOST: db
      APP_DB_PORT: 5432
      APP_DB_USER: postgres
      APP_DB_PASSWORD: secret
      APP_DB_NAME: agromart
      APP_JWT_SECRET: supersecretjwt-change-me-for-local-dev-if-you-want
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  client:
    build:
      context: apps/client
      dockerfile: Dockerfile
      
    container_name: agromart-client
    volumes:
      - ./apps/client:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080/api
    ports:
      - "3000:3000"

volumes:
  pgdata: