// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: analytics.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countExpiringBatchesWithinDays = `-- name: CountExpiringBatchesWithinDays :one
SELECT COALESCE(COUNT(*), 0) AS expiring_batches_count
FROM (
  SELECT b.id
  FROM batches b
  JOIN inventory i ON i.batch_id = b.id
  WHERE b.tenant_id = $1
    AND i.quantity > 0
    AND b.expiry_date IS NOT NULL
    AND b.expiry_date::date BETWEEN CURRENT_DATE AND ($2)::date
) t
`

type CountExpiringBatchesWithinDaysParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  time.Time `json:"column_2"`
}

// Pass an upper bound date (e.g., CURRENT_DATE + interval '30 days') from Go layer.
func (q *Queries) CountExpiringBatchesWithinDays(ctx context.Context, arg CountExpiringBatchesWithinDaysParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, countExpiringBatchesWithinDays, arg.TenantID, arg.Column2)
	var expiring_batches_count interface{}
	err := row.Scan(&expiring_batches_count)
	return expiring_batches_count, err
}

const countOpenPurchaseOrders = `-- name: CountOpenPurchaseOrders :one
SELECT COUNT(*) AS open_purchase_orders_count
FROM purchase_orders po
WHERE po.tenant_id = $1
  AND po.status IN ('DRAFT','ISSUED','RECEIVED')
  AND po.order_date BETWEEN $2 AND $3
`

type CountOpenPurchaseOrdersParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	OrderDate   time.Time `json:"order_date"`
	OrderDate_2 time.Time `json:"order_date_2"`
}

func (q *Queries) CountOpenPurchaseOrders(ctx context.Context, arg CountOpenPurchaseOrdersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpenPurchaseOrders, arg.TenantID, arg.OrderDate, arg.OrderDate_2)
	var open_purchase_orders_count int64
	err := row.Scan(&open_purchase_orders_count)
	return open_purchase_orders_count, err
}

const countOpenSalesOrders = `-- name: CountOpenSalesOrders :one
SELECT COUNT(*) AS open_sales_orders_count
FROM sales_orders so
WHERE so.tenant_id = $1
  AND so.status IN ('DRAFT','CONFIRMED','SHIPPED')
  AND so.order_date BETWEEN $2 AND $3
`

type CountOpenSalesOrdersParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	OrderDate   time.Time `json:"order_date"`
	OrderDate_2 time.Time `json:"order_date_2"`
}

func (q *Queries) CountOpenSalesOrders(ctx context.Context, arg CountOpenSalesOrdersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOpenSalesOrders, arg.TenantID, arg.OrderDate, arg.OrderDate_2)
	var open_sales_orders_count int64
	err := row.Scan(&open_sales_orders_count)
	return open_sales_orders_count, err
}

const getInventoryValueAnalytics = `-- name: GetInventoryValueAnalytics :one


SELECT COALESCE(SUM(i.quantity * b.cost), 0) AS total_value
FROM inventory i
JOIN batches b ON i.batch_id = b.id
WHERE i.tenant_id = $1
`

// Analytics and Reporting SQLC queries
// NOTE: Do NOT duplicate existing query names from other files.
// Inventory value already exists in inventory.sql as GetInventoryValue.
// Using a different name here for completeness if needed elsewhere.
func (q *Queries) GetInventoryValueAnalytics(ctx context.Context, tenantID uuid.UUID) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getInventoryValueAnalytics, tenantID)
	var total_value interface{}
	err := row.Scan(&total_value)
	return total_value, err
}

const getPurchasesTimeSeries = `-- name: GetPurchasesTimeSeries :many
SELECT
  date_trunc($1::text, po.order_date) AS period,
  COALESCE(SUM(poi.total_cost), 0) AS total_cost
FROM purchase_order_items poi
JOIN purchase_orders po
  ON po.id = poi.purchase_order_id
 AND po.tenant_id = poi.tenant_id
WHERE poi.tenant_id = $2
  AND po.status IN ('RECEIVED','CLOSED')
  AND po.order_date BETWEEN $3 AND $4
GROUP BY period
ORDER BY period
`

type GetPurchasesTimeSeriesParams struct {
	Grp      string    `json:"grp"`
	TenantID uuid.UUID `json:"tenant_id"`
	FromDate time.Time `json:"from_date"`
	ToDate   time.Time `json:"to_date"`
}

type GetPurchasesTimeSeriesRow struct {
	Period    int64       `json:"period"`
	TotalCost interface{} `json:"total_cost"`
}

func (q *Queries) GetPurchasesTimeSeries(ctx context.Context, arg GetPurchasesTimeSeriesParams) ([]GetPurchasesTimeSeriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getPurchasesTimeSeries,
		arg.Grp,
		arg.TenantID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPurchasesTimeSeriesRow{}
	for rows.Next() {
		var i GetPurchasesTimeSeriesRow
		if err := rows.Scan(&i.Period, &i.TotalCost); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRevenueInPeriod = `-- name: GetRevenueInPeriod :one
SELECT COALESCE(SUM(soi.total_price), 0) AS revenue_in_period
FROM sales_order_items soi
JOIN sales_orders so
  ON so.id = soi.sales_order_id
 AND so.tenant_id = soi.tenant_id
WHERE soi.tenant_id = $1
  AND so.status IN ('SHIPPED','DELIVERED')
  AND so.order_date BETWEEN $2 AND $3
`

type GetRevenueInPeriodParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	OrderDate   time.Time `json:"order_date"`
	OrderDate_2 time.Time `json:"order_date_2"`
}

func (q *Queries) GetRevenueInPeriod(ctx context.Context, arg GetRevenueInPeriodParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getRevenueInPeriod, arg.TenantID, arg.OrderDate, arg.OrderDate_2)
	var revenue_in_period interface{}
	err := row.Scan(&revenue_in_period)
	return revenue_in_period, err
}

const getSalesTimeSeries = `-- name: GetSalesTimeSeries :many
SELECT
  date_trunc($1::text, so.order_date) AS period,
  COALESCE(SUM(soi.total_price), 0) AS revenue
FROM sales_order_items soi
JOIN sales_orders so
  ON so.id = soi.sales_order_id
 AND so.tenant_id = soi.tenant_id
WHERE soi.tenant_id = $2
  AND so.status IN ('SHIPPED','DELIVERED')
  AND so.order_date BETWEEN $3 AND $4
GROUP BY period
ORDER BY period
`

type GetSalesTimeSeriesParams struct {
	Grp      string    `json:"grp"`
	TenantID uuid.UUID `json:"tenant_id"`
	FromDate time.Time `json:"from_date"`
	ToDate   time.Time `json:"to_date"`
}

type GetSalesTimeSeriesRow struct {
	Period  int64       `json:"period"`
	Revenue interface{} `json:"revenue"`
}

// grp is 'day' or 'month'
func (q *Queries) GetSalesTimeSeries(ctx context.Context, arg GetSalesTimeSeriesParams) ([]GetSalesTimeSeriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getSalesTimeSeries,
		arg.Grp,
		arg.TenantID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSalesTimeSeriesRow{}
	for rows.Next() {
		var i GetSalesTimeSeriesRow
		if err := rows.Scan(&i.Period, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStockoutRiskCount = `-- name: GetStockoutRiskCount :one
SELECT COALESCE(COUNT(*), 0) AS stockout_risk_count
FROM (
  SELECT p.id
  FROM products p
  LEFT JOIN inventory i
    ON i.product_id = p.id
   AND i.tenant_id = p.tenant_id
  WHERE p.tenant_id = $1
  GROUP BY p.id
  HAVING SUM(COALESCE(i.quantity, 0)) <= $2
) t
`

type GetStockoutRiskCountParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Quantity string    `json:"quantity"`
}

func (q *Queries) GetStockoutRiskCount(ctx context.Context, arg GetStockoutRiskCountParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getStockoutRiskCount, arg.TenantID, arg.Quantity)
	var stockout_risk_count interface{}
	err := row.Scan(&stockout_risk_count)
	return stockout_risk_count, err
}

const getTopProductsByRevenue = `-- name: GetTopProductsByRevenue :many
SELECT
  p.id        AS product_id,
  p.name      AS product_name,
  p.sku       AS product_sku,
  SUM(soi.total_price) AS revenue
FROM sales_order_items soi
JOIN sales_orders so
  ON so.id = soi.sales_order_id
 AND so.tenant_id = soi.tenant_id
JOIN products p
  ON p.id = soi.product_id
 AND p.tenant_id = soi.tenant_id
WHERE soi.tenant_id = $1
  AND so.status IN ('SHIPPED','DELIVERED')
  AND so.order_date BETWEEN $2 AND $3
GROUP BY p.id, p.name, p.sku
ORDER BY revenue DESC
LIMIT $4
`

type GetTopProductsByRevenueParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	OrderDate   time.Time `json:"order_date"`
	OrderDate_2 time.Time `json:"order_date_2"`
	Limit       int32     `json:"limit"`
}

type GetTopProductsByRevenueRow struct {
	ProductID   uuid.UUID `json:"product_id"`
	ProductName string    `json:"product_name"`
	ProductSku  string    `json:"product_sku"`
	Revenue     int64     `json:"revenue"`
}

func (q *Queries) GetTopProductsByRevenue(ctx context.Context, arg GetTopProductsByRevenueParams) ([]GetTopProductsByRevenueRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopProductsByRevenue,
		arg.TenantID,
		arg.OrderDate,
		arg.OrderDate_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopProductsByRevenueRow{}
	for rows.Next() {
		var i GetTopProductsByRevenueRow
		if err := rows.Scan(
			&i.ProductID,
			&i.ProductName,
			&i.ProductSku,
			&i.Revenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
