// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: batches.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createBatch = `-- name: CreateBatch :one
INSERT INTO batches (tenant_id, product_id, batch_number, expiry_date, cost)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, product_id, batch_number, expiry_date, cost, created_at
`

type CreateBatchParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	ProductID   uuid.UUID `json:"product_id"`
	BatchNumber string    `json:"batch_number"`
	ExpiryDate  time.Time `json:"expiry_date"`
	Cost        string    `json:"cost"`
}

func (q *Queries) CreateBatch(ctx context.Context, arg CreateBatchParams) (Batch, error) {
	row := q.db.QueryRowContext(ctx, createBatch,
		arg.TenantID,
		arg.ProductID,
		arg.BatchNumber,
		arg.ExpiryDate,
		arg.Cost,
	)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductID,
		&i.BatchNumber,
		&i.ExpiryDate,
		&i.Cost,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBatch = `-- name: DeleteBatch :exec
DELETE FROM batches
WHERE id = $1 AND tenant_id = $2
`

type DeleteBatchParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteBatch(ctx context.Context, arg DeleteBatchParams) error {
	_, err := q.db.ExecContext(ctx, deleteBatch, arg.ID, arg.TenantID)
	return err
}

const getBatchByID = `-- name: GetBatchByID :one
SELECT id, tenant_id, product_id, batch_number, expiry_date, cost, created_at FROM batches
WHERE id = $1 AND tenant_id = $2
`

type GetBatchByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetBatchByID(ctx context.Context, arg GetBatchByIDParams) (Batch, error) {
	row := q.db.QueryRowContext(ctx, getBatchByID, arg.ID, arg.TenantID)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductID,
		&i.BatchNumber,
		&i.ExpiryDate,
		&i.Cost,
		&i.CreatedAt,
	)
	return i, err
}

const listBatches = `-- name: ListBatches :many
SELECT id, tenant_id, product_id, batch_number, expiry_date, cost, created_at FROM batches
WHERE tenant_id = $1
ORDER BY id LIMIT $2 OFFSET $3
`

type ListBatchesParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListBatches(ctx context.Context, arg ListBatchesParams) ([]Batch, error) {
	rows, err := q.db.QueryContext(ctx, listBatches, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Batch{}
	for rows.Next() {
		var i Batch
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProductID,
			&i.BatchNumber,
			&i.ExpiryDate,
			&i.Cost,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBatch = `-- name: UpdateBatch :one
UPDATE batches
SET batch_number = $2, expiry_date = $3, cost = $4
WHERE id = $1 AND tenant_id = $5
RETURNING id, tenant_id, product_id, batch_number, expiry_date, cost, created_at
`

type UpdateBatchParams struct {
	ID          uuid.UUID `json:"id"`
	BatchNumber string    `json:"batch_number"`
	ExpiryDate  time.Time `json:"expiry_date"`
	Cost        string    `json:"cost"`
	TenantID    uuid.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateBatch(ctx context.Context, arg UpdateBatchParams) (Batch, error) {
	row := q.db.QueryRowContext(ctx, updateBatch,
		arg.ID,
		arg.BatchNumber,
		arg.ExpiryDate,
		arg.Cost,
		arg.TenantID,
	)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductID,
		&i.BatchNumber,
		&i.ExpiryDate,
		&i.Cost,
		&i.CreatedAt,
	)
	return i, err
}
