// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: files.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (
    tenant_id, original_name, file_name, file_path, file_size, mime_type,
    file_type, entity_type, entity_id, width, height, compression_applied,
    virus_scanned, virus_scan_status, checksum, bucket_name, object_key,
    is_public, uploaded_by, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15,
    $16, $17, $18, $19, $20
) RETURNING id, tenant_id, original_name, file_name, file_path, file_size, mime_type, file_type, entity_type, entity_id, width, height, compression_applied, virus_scanned, virus_scan_status, checksum, bucket_name, object_key, is_public, uploaded_by, expires_at, created_at, updated_at
`

type CreateFileParams struct {
	TenantID           uuid.UUID      `json:"tenant_id"`
	OriginalName       string         `json:"original_name"`
	FileName           string         `json:"file_name"`
	FilePath           string         `json:"file_path"`
	FileSize           int64          `json:"file_size"`
	MimeType           string         `json:"mime_type"`
	FileType           string         `json:"file_type"`
	EntityType         string         `json:"entity_type"`
	EntityID           uuid.UUID      `json:"entity_id"`
	Width              sql.NullInt32  `json:"width"`
	Height             sql.NullInt32  `json:"height"`
	CompressionApplied sql.NullBool   `json:"compression_applied"`
	VirusScanned       sql.NullBool   `json:"virus_scanned"`
	VirusScanStatus    sql.NullString `json:"virus_scan_status"`
	Checksum           sql.NullString `json:"checksum"`
	BucketName         string         `json:"bucket_name"`
	ObjectKey          string         `json:"object_key"`
	IsPublic           sql.NullBool   `json:"is_public"`
	UploadedBy         uuid.NullUUID  `json:"uploaded_by"`
	ExpiresAt          sql.NullTime   `json:"expires_at"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFile,
		arg.TenantID,
		arg.OriginalName,
		arg.FileName,
		arg.FilePath,
		arg.FileSize,
		arg.MimeType,
		arg.FileType,
		arg.EntityType,
		arg.EntityID,
		arg.Width,
		arg.Height,
		arg.CompressionApplied,
		arg.VirusScanned,
		arg.VirusScanStatus,
		arg.Checksum,
		arg.BucketName,
		arg.ObjectKey,
		arg.IsPublic,
		arg.UploadedBy,
		arg.ExpiresAt,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OriginalName,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.MimeType,
		&i.FileType,
		&i.EntityType,
		&i.EntityID,
		&i.Width,
		&i.Height,
		&i.CompressionApplied,
		&i.VirusScanned,
		&i.VirusScanStatus,
		&i.Checksum,
		&i.BucketName,
		&i.ObjectKey,
		&i.IsPublic,
		&i.UploadedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredFiles = `-- name: DeleteExpiredFiles :exec
DELETE FROM files WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredFiles(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredFiles)
	return err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files WHERE id = $1 AND tenant_id = $2
`

type DeleteFileParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteFile(ctx context.Context, arg DeleteFileParams) error {
	_, err := q.db.ExecContext(ctx, deleteFile, arg.ID, arg.TenantID)
	return err
}

const getFile = `-- name: GetFile :one
SELECT id, tenant_id, original_name, file_name, file_path, file_size, mime_type, file_type, entity_type, entity_id, width, height, compression_applied, virus_scanned, virus_scan_status, checksum, bucket_name, object_key, is_public, uploaded_by, expires_at, created_at, updated_at FROM files WHERE id = $1 AND tenant_id = $2
`

type GetFileParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetFile(ctx context.Context, arg GetFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, getFile, arg.ID, arg.TenantID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OriginalName,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.MimeType,
		&i.FileType,
		&i.EntityType,
		&i.EntityID,
		&i.Width,
		&i.Height,
		&i.CompressionApplied,
		&i.VirusScanned,
		&i.VirusScanStatus,
		&i.Checksum,
		&i.BucketName,
		&i.ObjectKey,
		&i.IsPublic,
		&i.UploadedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileByChecksum = `-- name: GetFileByChecksum :one
SELECT id, tenant_id, original_name, file_name, file_path, file_size, mime_type, file_type, entity_type, entity_id, width, height, compression_applied, virus_scanned, virus_scan_status, checksum, bucket_name, object_key, is_public, uploaded_by, expires_at, created_at, updated_at FROM files
WHERE checksum = $1 AND tenant_id = $2
`

type GetFileByChecksumParams struct {
	Checksum sql.NullString `json:"checksum"`
	TenantID uuid.UUID      `json:"tenant_id"`
}

func (q *Queries) GetFileByChecksum(ctx context.Context, arg GetFileByChecksumParams) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByChecksum, arg.Checksum, arg.TenantID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OriginalName,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.MimeType,
		&i.FileType,
		&i.EntityType,
		&i.EntityID,
		&i.Width,
		&i.Height,
		&i.CompressionApplied,
		&i.VirusScanned,
		&i.VirusScanStatus,
		&i.Checksum,
		&i.BucketName,
		&i.ObjectKey,
		&i.IsPublic,
		&i.UploadedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFilesByEntity = `-- name: GetFilesByEntity :many
SELECT id, tenant_id, original_name, file_name, file_path, file_size, mime_type, file_type, entity_type, entity_id, width, height, compression_applied, virus_scanned, virus_scan_status, checksum, bucket_name, object_key, is_public, uploaded_by, expires_at, created_at, updated_at FROM files
WHERE entity_type = $1 AND entity_id = $2 AND tenant_id = $3
ORDER BY created_at DESC
`

type GetFilesByEntityParams struct {
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
	TenantID   uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetFilesByEntity(ctx context.Context, arg GetFilesByEntityParams) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, getFilesByEntity, arg.EntityType, arg.EntityID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OriginalName,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.MimeType,
			&i.FileType,
			&i.EntityType,
			&i.EntityID,
			&i.Width,
			&i.Height,
			&i.CompressionApplied,
			&i.VirusScanned,
			&i.VirusScanStatus,
			&i.Checksum,
			&i.BucketName,
			&i.ObjectKey,
			&i.IsPublic,
			&i.UploadedBy,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesByMimeType = `-- name: GetFilesByMimeType :many
SELECT id, tenant_id, original_name, file_name, file_path, file_size, mime_type, file_type, entity_type, entity_id, width, height, compression_applied, virus_scanned, virus_scan_status, checksum, bucket_name, object_key, is_public, uploaded_by, expires_at, created_at, updated_at FROM files
WHERE mime_type = $1 AND tenant_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type GetFilesByMimeTypeParams struct {
	MimeType string    `json:"mime_type"`
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) GetFilesByMimeType(ctx context.Context, arg GetFilesByMimeTypeParams) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, getFilesByMimeType,
		arg.MimeType,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OriginalName,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.MimeType,
			&i.FileType,
			&i.EntityType,
			&i.EntityID,
			&i.Width,
			&i.Height,
			&i.CompressionApplied,
			&i.VirusScanned,
			&i.VirusScanStatus,
			&i.Checksum,
			&i.BucketName,
			&i.ObjectKey,
			&i.IsPublic,
			&i.UploadedBy,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesByType = `-- name: GetFilesByType :many
SELECT id, tenant_id, original_name, file_name, file_path, file_size, mime_type, file_type, entity_type, entity_id, width, height, compression_applied, virus_scanned, virus_scan_status, checksum, bucket_name, object_key, is_public, uploaded_by, expires_at, created_at, updated_at FROM files
WHERE file_type = $1 AND tenant_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type GetFilesByTypeParams struct {
	FileType string    `json:"file_type"`
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) GetFilesByType(ctx context.Context, arg GetFilesByTypeParams) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, getFilesByType,
		arg.FileType,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OriginalName,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.MimeType,
			&i.FileType,
			&i.EntityType,
			&i.EntityID,
			&i.Width,
			&i.Height,
			&i.CompressionApplied,
			&i.VirusScanned,
			&i.VirusScanStatus,
			&i.Checksum,
			&i.BucketName,
			&i.ObjectKey,
			&i.IsPublic,
			&i.UploadedBy,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesByUser = `-- name: GetFilesByUser :many
SELECT id, tenant_id, original_name, file_name, file_path, file_size, mime_type, file_type, entity_type, entity_id, width, height, compression_applied, virus_scanned, virus_scan_status, checksum, bucket_name, object_key, is_public, uploaded_by, expires_at, created_at, updated_at FROM files
WHERE uploaded_by = $1 AND tenant_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type GetFilesByUserParams struct {
	UploadedBy uuid.NullUUID `json:"uploaded_by"`
	TenantID   uuid.UUID     `json:"tenant_id"`
	Limit      int32         `json:"limit"`
	Offset     int32         `json:"offset"`
}

func (q *Queries) GetFilesByUser(ctx context.Context, arg GetFilesByUserParams) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, getFilesByUser,
		arg.UploadedBy,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OriginalName,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.MimeType,
			&i.FileType,
			&i.EntityType,
			&i.EntityID,
			&i.Width,
			&i.Height,
			&i.CompressionApplied,
			&i.VirusScanned,
			&i.VirusScanStatus,
			&i.Checksum,
			&i.BucketName,
			&i.ObjectKey,
			&i.IsPublic,
			&i.UploadedBy,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingVirusScans = `-- name: GetPendingVirusScans :many
SELECT id, tenant_id, original_name, file_name, file_path, file_size, mime_type, file_type, entity_type, entity_id, width, height, compression_applied, virus_scanned, virus_scan_status, checksum, bucket_name, object_key, is_public, uploaded_by, expires_at, created_at, updated_at FROM files
WHERE virus_scanned = false AND tenant_id = $1
ORDER BY created_at ASC
LIMIT $2
`

type GetPendingVirusScansParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
}

func (q *Queries) GetPendingVirusScans(ctx context.Context, arg GetPendingVirusScansParams) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, getPendingVirusScans, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OriginalName,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.MimeType,
			&i.FileType,
			&i.EntityType,
			&i.EntityID,
			&i.Width,
			&i.Height,
			&i.CompressionApplied,
			&i.VirusScanned,
			&i.VirusScanStatus,
			&i.Checksum,
			&i.BucketName,
			&i.ObjectKey,
			&i.IsPublic,
			&i.UploadedBy,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFileMetadata = `-- name: UpdateFileMetadata :exec
UPDATE files
SET width = $1, height = $2, compression_applied = $3, checksum = $4, updated_at = NOW()
WHERE id = $5
`

type UpdateFileMetadataParams struct {
	Width              sql.NullInt32  `json:"width"`
	Height             sql.NullInt32  `json:"height"`
	CompressionApplied sql.NullBool   `json:"compression_applied"`
	Checksum           sql.NullString `json:"checksum"`
	ID                 uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateFileMetadata(ctx context.Context, arg UpdateFileMetadataParams) error {
	_, err := q.db.ExecContext(ctx, updateFileMetadata,
		arg.Width,
		arg.Height,
		arg.CompressionApplied,
		arg.Checksum,
		arg.ID,
	)
	return err
}

const updateFileVirusScan = `-- name: UpdateFileVirusScan :exec
UPDATE files
SET virus_scanned = $1, virus_scan_status = $2, updated_at = NOW()
WHERE id = $3
`

type UpdateFileVirusScanParams struct {
	VirusScanned    sql.NullBool   `json:"virus_scanned"`
	VirusScanStatus sql.NullString `json:"virus_scan_status"`
	ID              uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateFileVirusScan(ctx context.Context, arg UpdateFileVirusScanParams) error {
	_, err := q.db.ExecContext(ctx, updateFileVirusScan, arg.VirusScanned, arg.VirusScanStatus, arg.ID)
	return err
}
