// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: locations.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (tenant_id, name, address, city, state, postal_code, country, phone, email, location_type, capacity, capacity_unit, manager_id, operating_hours, temperature_controlled, security_level, is_active, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
RETURNING id, tenant_id, name, address, city, state, postal_code, country, phone, email, location_type, capacity, capacity_unit, manager_id, operating_hours, temperature_controlled, security_level, is_active, notes, created_at, updated_at
`

type CreateLocationParams struct {
	TenantID              uuid.UUID      `json:"tenant_id"`
	Name                  string         `json:"name"`
	Address               sql.NullString `json:"address"`
	City                  sql.NullString `json:"city"`
	State                 sql.NullString `json:"state"`
	PostalCode            sql.NullString `json:"postal_code"`
	Country               sql.NullString `json:"country"`
	Phone                 sql.NullString `json:"phone"`
	Email                 sql.NullString `json:"email"`
	LocationType          string         `json:"location_type"`
	Capacity              sql.NullString `json:"capacity"`
	CapacityUnit          sql.NullString `json:"capacity_unit"`
	ManagerID             uuid.NullUUID  `json:"manager_id"`
	OperatingHours        sql.NullString `json:"operating_hours"`
	TemperatureControlled bool           `json:"temperature_controlled"`
	SecurityLevel         sql.NullString `json:"security_level"`
	IsActive              bool           `json:"is_active"`
	Notes                 sql.NullString `json:"notes"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRowContext(ctx, createLocation,
		arg.TenantID,
		arg.Name,
		arg.Address,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Country,
		arg.Phone,
		arg.Email,
		arg.LocationType,
		arg.Capacity,
		arg.CapacityUnit,
		arg.ManagerID,
		arg.OperatingHours,
		arg.TemperatureControlled,
		arg.SecurityLevel,
		arg.IsActive,
		arg.Notes,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.Phone,
		&i.Email,
		&i.LocationType,
		&i.Capacity,
		&i.CapacityUnit,
		&i.ManagerID,
		&i.OperatingHours,
		&i.TemperatureControlled,
		&i.SecurityLevel,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLocation = `-- name: DeleteLocation :exec
UPDATE locations
SET is_active = FALSE, updated_at = NOW()
WHERE id = $1 AND tenant_id = $2
`

type DeleteLocationParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteLocation(ctx context.Context, arg DeleteLocationParams) error {
	_, err := q.db.ExecContext(ctx, deleteLocation, arg.ID, arg.TenantID)
	return err
}

const getLocationByID = `-- name: GetLocationByID :one
SELECT id, tenant_id, name, address, city, state, postal_code, country, phone, email, location_type, capacity, capacity_unit, manager_id, operating_hours, temperature_controlled, security_level, is_active, notes, created_at, updated_at FROM locations
WHERE id = $1 AND tenant_id = $2
`

type GetLocationByIDParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetLocationByID(ctx context.Context, arg GetLocationByIDParams) (Location, error) {
	row := q.db.QueryRowContext(ctx, getLocationByID, arg.ID, arg.TenantID)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.Phone,
		&i.Email,
		&i.LocationType,
		&i.Capacity,
		&i.CapacityUnit,
		&i.ManagerID,
		&i.OperatingHours,
		&i.TemperatureControlled,
		&i.SecurityLevel,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLocationsByManager = `-- name: GetLocationsByManager :many
SELECT id, tenant_id, name, address, city, state, postal_code, country, phone, email, location_type, capacity, capacity_unit, manager_id, operating_hours, temperature_controlled, security_level, is_active, notes, created_at, updated_at FROM locations
WHERE tenant_id = $1 AND manager_id = $2 AND is_active = TRUE
ORDER BY name
`

type GetLocationsByManagerParams struct {
	TenantID  uuid.UUID     `json:"tenant_id"`
	ManagerID uuid.NullUUID `json:"manager_id"`
}

func (q *Queries) GetLocationsByManager(ctx context.Context, arg GetLocationsByManagerParams) ([]Location, error) {
	rows, err := q.db.QueryContext(ctx, getLocationsByManager, arg.TenantID, arg.ManagerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Address,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.Country,
			&i.Phone,
			&i.Email,
			&i.LocationType,
			&i.Capacity,
			&i.CapacityUnit,
			&i.ManagerID,
			&i.OperatingHours,
			&i.TemperatureControlled,
			&i.SecurityLevel,
			&i.IsActive,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLocationsWithCapacity = `-- name: GetLocationsWithCapacity :many
SELECT id, tenant_id, name, address, city, state, postal_code, country, phone, email, location_type, capacity, capacity_unit, manager_id, operating_hours, temperature_controlled, security_level, is_active, notes, created_at, updated_at FROM locations
WHERE tenant_id = $1 AND capacity IS NOT NULL AND is_active = TRUE
ORDER BY capacity DESC
`

func (q *Queries) GetLocationsWithCapacity(ctx context.Context, tenantID uuid.UUID) ([]Location, error) {
	rows, err := q.db.QueryContext(ctx, getLocationsWithCapacity, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Address,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.Country,
			&i.Phone,
			&i.Email,
			&i.LocationType,
			&i.Capacity,
			&i.CapacityUnit,
			&i.ManagerID,
			&i.OperatingHours,
			&i.TemperatureControlled,
			&i.SecurityLevel,
			&i.IsActive,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveLocations = `-- name: ListActiveLocations :many
SELECT id, tenant_id, name, address, city, state, postal_code, country, phone, email, location_type, capacity, capacity_unit, manager_id, operating_hours, temperature_controlled, security_level, is_active, notes, created_at, updated_at FROM locations
WHERE tenant_id = $1 AND is_active = TRUE
ORDER BY name
`

func (q *Queries) ListActiveLocations(ctx context.Context, tenantID uuid.UUID) ([]Location, error) {
	rows, err := q.db.QueryContext(ctx, listActiveLocations, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Address,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.Country,
			&i.Phone,
			&i.Email,
			&i.LocationType,
			&i.Capacity,
			&i.CapacityUnit,
			&i.ManagerID,
			&i.OperatingHours,
			&i.TemperatureControlled,
			&i.SecurityLevel,
			&i.IsActive,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocations = `-- name: ListLocations :many
SELECT id, tenant_id, name, address, city, state, postal_code, country, phone, email, location_type, capacity, capacity_unit, manager_id, operating_hours, temperature_controlled, security_level, is_active, notes, created_at, updated_at FROM locations
WHERE tenant_id = $1 AND location_type = $2 AND is_active = $3
ORDER BY name
LIMIT $4 OFFSET $5
`

type ListLocationsParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	LocationType string    `json:"location_type"`
	IsActive     bool      `json:"is_active"`
	Limit        int32     `json:"limit"`
	Offset       int32     `json:"offset"`
}

func (q *Queries) ListLocations(ctx context.Context, arg ListLocationsParams) ([]Location, error) {
	rows, err := q.db.QueryContext(ctx, listLocations,
		arg.TenantID,
		arg.LocationType,
		arg.IsActive,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Address,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.Country,
			&i.Phone,
			&i.Email,
			&i.LocationType,
			&i.Capacity,
			&i.CapacityUnit,
			&i.ManagerID,
			&i.OperatingHours,
			&i.TemperatureControlled,
			&i.SecurityLevel,
			&i.IsActive,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocationsByType = `-- name: ListLocationsByType :many
SELECT id, tenant_id, name, address, city, state, postal_code, country, phone, email, location_type, capacity, capacity_unit, manager_id, operating_hours, temperature_controlled, security_level, is_active, notes, created_at, updated_at FROM locations
WHERE tenant_id = $1 AND location_type = $2
ORDER BY name
`

type ListLocationsByTypeParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	LocationType string    `json:"location_type"`
}

func (q *Queries) ListLocationsByType(ctx context.Context, arg ListLocationsByTypeParams) ([]Location, error) {
	rows, err := q.db.QueryContext(ctx, listLocationsByType, arg.TenantID, arg.LocationType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Address,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.Country,
			&i.Phone,
			&i.Email,
			&i.LocationType,
			&i.Capacity,
			&i.CapacityUnit,
			&i.ManagerID,
			&i.OperatingHours,
			&i.TemperatureControlled,
			&i.SecurityLevel,
			&i.IsActive,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLocation = `-- name: UpdateLocation :one
UPDATE locations
SET name = $2, address = $3, city = $4, state = $5, postal_code = $6, country = $7, phone = $8, email = $9, location_type = $10, capacity = $11, capacity_unit = $12, manager_id = $13, operating_hours = $14, temperature_controlled = $15, security_level = $16, is_active = $17, notes = $18, updated_at = NOW()
WHERE id = $1 AND tenant_id = $19
RETURNING id, tenant_id, name, address, city, state, postal_code, country, phone, email, location_type, capacity, capacity_unit, manager_id, operating_hours, temperature_controlled, security_level, is_active, notes, created_at, updated_at
`

type UpdateLocationParams struct {
	ID                    uuid.UUID      `json:"id"`
	Name                  string         `json:"name"`
	Address               sql.NullString `json:"address"`
	City                  sql.NullString `json:"city"`
	State                 sql.NullString `json:"state"`
	PostalCode            sql.NullString `json:"postal_code"`
	Country               sql.NullString `json:"country"`
	Phone                 sql.NullString `json:"phone"`
	Email                 sql.NullString `json:"email"`
	LocationType          string         `json:"location_type"`
	Capacity              sql.NullString `json:"capacity"`
	CapacityUnit          sql.NullString `json:"capacity_unit"`
	ManagerID             uuid.NullUUID  `json:"manager_id"`
	OperatingHours        sql.NullString `json:"operating_hours"`
	TemperatureControlled bool           `json:"temperature_controlled"`
	SecurityLevel         sql.NullString `json:"security_level"`
	IsActive              bool           `json:"is_active"`
	Notes                 sql.NullString `json:"notes"`
	TenantID              uuid.UUID      `json:"tenant_id"`
}

func (q *Queries) UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error) {
	row := q.db.QueryRowContext(ctx, updateLocation,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Country,
		arg.Phone,
		arg.Email,
		arg.LocationType,
		arg.Capacity,
		arg.CapacityUnit,
		arg.ManagerID,
		arg.OperatingHours,
		arg.TemperatureControlled,
		arg.SecurityLevel,
		arg.IsActive,
		arg.Notes,
		arg.TenantID,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Address,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.Phone,
		&i.Email,
		&i.LocationType,
		&i.Capacity,
		&i.CapacityUnit,
		&i.ManagerID,
		&i.OperatingHours,
		&i.TemperatureControlled,
		&i.SecurityLevel,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
