// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Batch struct {
	ID          uuid.UUID      `json:"id"`
	TenantID    uuid.UUID      `json:"tenant_id"`
	ProductID   uuid.UUID      `json:"product_id"`
	BatchNumber string         `json:"batch_number"`
	ExpiryDate  time.Time      `json:"expiry_date"`
	Cost        pgtype.Numeric `json:"cost"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Customer struct {
	ID            uuid.UUID   `json:"id"`
	TenantID      uuid.UUID   `json:"tenant_id"`
	Name          string      `json:"name"`
	ContactPerson pgtype.Text `json:"contact_person"`
	Email         pgtype.Text `json:"email"`
	Phone         pgtype.Text `json:"phone"`
	Address       pgtype.Text `json:"address"`
	PaymentMode   pgtype.Text `json:"payment_mode"`
	IsActive      pgtype.Bool `json:"is_active"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
}

type Inventory struct {
	ID        uuid.UUID      `json:"id"`
	TenantID  uuid.UUID      `json:"tenant_id"`
	ProductID uuid.UUID      `json:"product_id"`
	BatchID   uuid.UUID      `json:"batch_id"`
	Quantity  pgtype.Numeric `json:"quantity"`
}

type InventoryLog struct {
	ID              uuid.UUID      `json:"id"`
	TenantID        uuid.UUID      `json:"tenant_id"`
	ProductID       uuid.UUID      `json:"product_id"`
	BatchID         uuid.UUID      `json:"batch_id"`
	TransactionType string         `json:"transaction_type"`
	QuantityChange  pgtype.Numeric `json:"quantity_change"`
	TransactionDate time.Time      `json:"transaction_date"`
	Notes           pgtype.Text    `json:"notes"`
	ReferenceID     pgtype.UUID    `json:"reference_id"`
}

type Location struct {
	ID           uuid.UUID   `json:"id"`
	TenantID     uuid.UUID   `json:"tenant_id"`
	Name         string      `json:"name"`
	Address      pgtype.Text `json:"address"`
	City         pgtype.Text `json:"city"`
	State        pgtype.Text `json:"state"`
	PostalCode   pgtype.Text `json:"postal_code"`
	Country      pgtype.Text `json:"country"`
	Phone        pgtype.Text `json:"phone"`
	Email        pgtype.Text `json:"email"`
	LocationType string      `json:"location_type"`
	IsActive     bool        `json:"is_active"`
	Notes        pgtype.Text `json:"notes"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type Product struct {
	ID           uuid.UUID      `json:"id"`
	TenantID     uuid.UUID      `json:"tenant_id"`
	Sku          string         `json:"sku"`
	Name         string         `json:"name"`
	Price        pgtype.Numeric `json:"price"`
	Description  pgtype.Text    `json:"description"`
	ImageUrl     pgtype.Text    `json:"image_url"`
	Brand        pgtype.Text    `json:"brand"`
	UnitID       uuid.UUID      `json:"unit_id"`
	PricePerUnit pgtype.Numeric `json:"price_per_unit"`
	GstPercent   pgtype.Numeric `json:"gst_percent"`
	CreatedAt    time.Time      `json:"created_at"`
}

type PurchaseOrder struct {
	ID                   uuid.UUID          `json:"id"`
	TenantID             uuid.UUID          `json:"tenant_id"`
	PoNumber             string             `json:"po_number"`
	SupplierID           uuid.UUID          `json:"supplier_id"`
	LocationID           pgtype.UUID        `json:"location_id"`
	OrderDate            time.Time          `json:"order_date"`
	ExpectedDeliveryDate pgtype.Date        `json:"expected_delivery_date"`
	ActualDeliveryDate   pgtype.Date        `json:"actual_delivery_date"`
	TotalAmount          pgtype.Numeric     `json:"total_amount"`
	TaxAmount            pgtype.Numeric     `json:"tax_amount"`
	DiscountAmount       pgtype.Numeric     `json:"discount_amount"`
	FinalAmount          pgtype.Numeric     `json:"final_amount"`
	Status               string             `json:"status"`
	Notes                pgtype.Text        `json:"notes"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
	ApprovedBy           pgtype.UUID        `json:"approved_by"`
	ApprovedAt           pgtype.Timestamptz `json:"approved_at"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
}

type PurchaseOrderItem struct {
	ID               uuid.UUID      `json:"id"`
	TenantID         uuid.UUID      `json:"tenant_id"`
	PurchaseOrderID  uuid.UUID      `json:"purchase_order_id"`
	ProductID        uuid.UUID      `json:"product_id"`
	BatchID          pgtype.UUID    `json:"batch_id"`
	QuantityOrdered  pgtype.Numeric `json:"quantity_ordered"`
	QuantityReceived pgtype.Numeric `json:"quantity_received"`
	UnitCost         pgtype.Numeric `json:"unit_cost"`
	TotalCost        pgtype.Numeric `json:"total_cost"`
	TaxPercent       pgtype.Numeric `json:"tax_percent"`
	DiscountPercent  pgtype.Numeric `json:"discount_percent"`
	Notes            pgtype.Text    `json:"notes"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

type SalesOrder struct {
	ID                   uuid.UUID          `json:"id"`
	TenantID             uuid.UUID          `json:"tenant_id"`
	SoNumber             string             `json:"so_number"`
	CustomerID           uuid.UUID          `json:"customer_id"`
	LocationID           pgtype.UUID        `json:"location_id"`
	OrderDate            time.Time          `json:"order_date"`
	ExpectedDeliveryDate pgtype.Date        `json:"expected_delivery_date"`
	ActualDeliveryDate   pgtype.Date        `json:"actual_delivery_date"`
	TotalAmount          pgtype.Numeric     `json:"total_amount"`
	TaxAmount            pgtype.Numeric     `json:"tax_amount"`
	DiscountAmount       pgtype.Numeric     `json:"discount_amount"`
	FinalAmount          pgtype.Numeric     `json:"final_amount"`
	Status               string             `json:"status"`
	Notes                pgtype.Text        `json:"notes"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
	ApprovedBy           pgtype.UUID        `json:"approved_by"`
	ApprovedAt           pgtype.Timestamptz `json:"approved_at"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
}

type SalesOrderItem struct {
	ID              uuid.UUID      `json:"id"`
	TenantID        uuid.UUID      `json:"tenant_id"`
	SalesOrderID    uuid.UUID      `json:"sales_order_id"`
	ProductID       uuid.UUID      `json:"product_id"`
	BatchID         pgtype.UUID    `json:"batch_id"`
	QuantityOrdered pgtype.Numeric `json:"quantity_ordered"`
	QuantityShipped pgtype.Numeric `json:"quantity_shipped"`
	UnitPrice       pgtype.Numeric `json:"unit_price"`
	TotalPrice      pgtype.Numeric `json:"total_price"`
	TaxPercent      pgtype.Numeric `json:"tax_percent"`
	DiscountPercent pgtype.Numeric `json:"discount_percent"`
	Notes           pgtype.Text    `json:"notes"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type Supplier struct {
	ID            uuid.UUID   `json:"id"`
	TenantID      uuid.UUID   `json:"tenant_id"`
	Name          string      `json:"name"`
	ContactPerson pgtype.Text `json:"contact_person"`
	Email         pgtype.Text `json:"email"`
	Phone         pgtype.Text `json:"phone"`
	Address       pgtype.Text `json:"address"`
	TaxID         pgtype.Text `json:"tax_id"`
	PaymentMode   pgtype.Text `json:"payment_mode"`
	IsActive      pgtype.Bool `json:"is_active"`
}

type Tenant struct {
	ID                 uuid.UUID   `json:"id"`
	Name               string      `json:"name"`
	Email              string      `json:"email"`
	Phone              string      `json:"phone"`
	Address            pgtype.Text `json:"address"`
	RegistrationNumber pgtype.Text `json:"registration_number"`
	IsActive           bool        `json:"is_active"`
	CreatedAt          time.Time   `json:"created_at"`
}

type Unit struct {
	ID           uuid.UUID `json:"id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	Name         string    `json:"name"`
	Abbreviation string    `json:"abbreviation"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	ID            uuid.UUID   `json:"id"`
	Name          string      `json:"name"`
	Email         string      `json:"email"`
	Password      string      `json:"password"`
	Phone         string      `json:"phone"`
	TenantID      uuid.UUID   `json:"tenant_id"`
	Role          interface{} `json:"role"`
	EmailVerified pgtype.Bool `json:"email_verified"`
	IsActive      pgtype.Bool `json:"is_active"`
	CreatedAt     time.Time   `json:"created_at"`
}
