// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddInventoryQuantity(ctx context.Context, arg AddInventoryQuantityParams) error
	CheckCustomerExists(ctx context.Context, arg CheckCustomerExistsParams) (bool, error)
	CheckProductExists(ctx context.Context, arg CheckProductExistsParams) (bool, error)
	CheckSupplierExists(ctx context.Context, arg CheckSupplierExistsParams) (bool, error)
	CountCustomers(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountProducts(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountProductsByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountSuppliers(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CreateBatch(ctx context.Context, arg CreateBatchParams) (Batch, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateInventoryLog(ctx context.Context, arg CreateInventoryLogParams) error
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (PurchaseOrder, error)
	CreatePurchaseOrderItem(ctx context.Context, arg CreatePurchaseOrderItemParams) (PurchaseOrderItem, error)
	CreateSalesOrder(ctx context.Context, arg CreateSalesOrderParams) (SalesOrder, error)
	CreateSalesOrderItem(ctx context.Context, arg CreateSalesOrderItemParams) (SalesOrderItem, error)
	CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUnit(ctx context.Context, arg CreateUnitParams) (Unit, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateCustomer(ctx context.Context, arg DeactivateCustomerParams) error
	DeactivateSupplier(ctx context.Context, arg DeactivateSupplierParams) error
	GetBatchByID(ctx context.Context, arg GetBatchByIDParams) (Batch, error)
	GetCustomerByID(ctx context.Context, arg GetCustomerByIDParams) (Customer, error)
	GetCustomerByName(ctx context.Context, arg GetCustomerByNameParams) (Customer, error)
	GetCustomerSalesSummary(ctx context.Context, tenantID uuid.UUID) ([]GetCustomerSalesSummaryRow, error)
	GetExpiringBatches(ctx context.Context, arg GetExpiringBatchesParams) ([]GetExpiringBatchesRow, error)
	GetInventoryByProductBatch(ctx context.Context, arg GetInventoryByProductBatchParams) (Inventory, error)
	GetInventoryLogByBatch(ctx context.Context, arg GetInventoryLogByBatchParams) ([]InventoryLog, error)
	GetInventoryLogByProduct(ctx context.Context, arg GetInventoryLogByProductParams) ([]InventoryLog, error)
	GetInventoryValue(ctx context.Context, tenantID uuid.UUID) (interface{}, error)
	GetLocationByID(ctx context.Context, arg GetLocationByIDParams) (Location, error)
	GetLowStockReport(ctx context.Context, arg GetLowStockReportParams) ([]GetLowStockReportRow, error)
	GetProductByID(ctx context.Context, arg GetProductByIDParams) (Product, error)
	GetProductBySKU(ctx context.Context, arg GetProductBySKUParams) (Product, error)
	GetProductInventoryDetails(ctx context.Context, arg GetProductInventoryDetailsParams) ([]GetProductInventoryDetailsRow, error)
	GetProductMovementReport(ctx context.Context, tenantID uuid.UUID) ([]GetProductMovementReportRow, error)
	GetProductQuantity(ctx context.Context, arg GetProductQuantityParams) (interface{}, error)
	GetPurchaseOrder(ctx context.Context, arg GetPurchaseOrderParams) (PurchaseOrder, error)
	GetPurchaseOrderItemByID(ctx context.Context, arg GetPurchaseOrderItemByIDParams) (PurchaseOrderItem, error)
	GetPurchaseOrderItems(ctx context.Context, arg GetPurchaseOrderItemsParams) ([]PurchaseOrderItem, error)
	GetSalesOrder(ctx context.Context, arg GetSalesOrderParams) (SalesOrder, error)
	GetSalesOrderItemByID(ctx context.Context, arg GetSalesOrderItemByIDParams) (SalesOrderItem, error)
	GetSalesOrderItems(ctx context.Context, arg GetSalesOrderItemsParams) ([]SalesOrderItem, error)
	GetSalesReportByDate(ctx context.Context, arg GetSalesReportByDateParams) ([]GetSalesReportByDateRow, error)
	GetSupplierByID(ctx context.Context, arg GetSupplierByIDParams) (Supplier, error)
	GetSupplierByName(ctx context.Context, arg GetSupplierByNameParams) (Supplier, error)
	GetSupplierPurchaseSummary(ctx context.Context, tenantID uuid.UUID) ([]GetSupplierPurchaseSummaryRow, error)
	GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetUnitByID(ctx context.Context, arg GetUnitByIDParams) (Unit, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListActiveCustomers(ctx context.Context, arg ListActiveCustomersParams) ([]Customer, error)
	ListActiveSuppliers(ctx context.Context, arg ListActiveSuppliersParams) ([]Supplier, error)
	ListAllInventory(ctx context.Context, arg ListAllInventoryParams) ([]ListAllInventoryRow, error)
	ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error)
	ListLocations(ctx context.Context, arg ListLocationsParams) ([]Location, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListPurchaseOrdersByStatus(ctx context.Context, arg ListPurchaseOrdersByStatusParams) ([]PurchaseOrder, error)
	ListPurchaseOrdersBySupplier(ctx context.Context, arg ListPurchaseOrdersBySupplierParams) ([]PurchaseOrder, error)
	ListSalesOrdersByCustomer(ctx context.Context, arg ListSalesOrdersByCustomerParams) ([]SalesOrder, error)
	ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]Supplier, error)
	ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error)
	ListUnits(ctx context.Context, arg ListUnitsParams) ([]Unit, error)
	ListUsersByRole(ctx context.Context, arg ListUsersByRoleParams) ([]User, error)
	ReduceInventoryQuantity(ctx context.Context, arg ReduceInventoryQuantityParams) error
	SearchCustomers(ctx context.Context, arg SearchCustomersParams) ([]Customer, error)
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error)
	SearchSuppliers(ctx context.Context, arg SearchSuppliersParams) ([]Supplier, error)
	SetInventoryQuantity(ctx context.Context, arg SetInventoryQuantityParams) error
	UpdateBatch(ctx context.Context, arg UpdateBatchParams) (Batch, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdateLocation(ctx context.Context, arg UpdateLocationParams) (Location, error)
	UpdateProductDetails(ctx context.Context, arg UpdateProductDetailsParams) (Product, error)
	UpdateProductPatch(ctx context.Context, arg UpdateProductPatchParams) error
	UpdatePurchaseOrderItemQuantityReceived(ctx context.Context, arg UpdatePurchaseOrderItemQuantityReceivedParams) (PurchaseOrderItem, error)
	UpdatePurchaseOrderStatus(ctx context.Context, arg UpdatePurchaseOrderStatusParams) error
	UpdateSalesOrderItemQuantityShipped(ctx context.Context, arg UpdateSalesOrderItemQuantityShippedParams) (SalesOrderItem, error)
	UpdateSalesOrderStatus(ctx context.Context, arg UpdateSalesOrderStatusParams) error
	UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
	UpdateUnit(ctx context.Context, arg UpdateUnitParams) (Unit, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
