// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: settings.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createNotificationSettings = `-- name: CreateNotificationSettings :one
INSERT INTO notification_settings (
    tenant_id, user_id, email_notifications, sms_notifications,
    push_notifications, low_stock_alerts, expiry_alerts,
    order_updates, payment_reminders, marketing_emails, weekly_reports
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, tenant_id, user_id, email_notifications, sms_notifications, push_notifications, low_stock_alerts, expiry_alerts, order_updates, payment_reminders, marketing_emails, weekly_reports, created_at, updated_at
`

type CreateNotificationSettingsParams struct {
	TenantID           uuid.UUID    `json:"tenant_id"`
	UserID             uuid.UUID    `json:"user_id"`
	EmailNotifications sql.NullBool `json:"email_notifications"`
	SmsNotifications   sql.NullBool `json:"sms_notifications"`
	PushNotifications  sql.NullBool `json:"push_notifications"`
	LowStockAlerts     sql.NullBool `json:"low_stock_alerts"`
	ExpiryAlerts       sql.NullBool `json:"expiry_alerts"`
	OrderUpdates       sql.NullBool `json:"order_updates"`
	PaymentReminders   sql.NullBool `json:"payment_reminders"`
	MarketingEmails    sql.NullBool `json:"marketing_emails"`
	WeeklyReports      sql.NullBool `json:"weekly_reports"`
}

func (q *Queries) CreateNotificationSettings(ctx context.Context, arg CreateNotificationSettingsParams) (NotificationSetting, error) {
	row := q.db.QueryRowContext(ctx, createNotificationSettings,
		arg.TenantID,
		arg.UserID,
		arg.EmailNotifications,
		arg.SmsNotifications,
		arg.PushNotifications,
		arg.LowStockAlerts,
		arg.ExpiryAlerts,
		arg.OrderUpdates,
		arg.PaymentReminders,
		arg.MarketingEmails,
		arg.WeeklyReports,
	)
	var i NotificationSetting
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.EmailNotifications,
		&i.SmsNotifications,
		&i.PushNotifications,
		&i.LowStockAlerts,
		&i.ExpiryAlerts,
		&i.OrderUpdates,
		&i.PaymentReminders,
		&i.MarketingEmails,
		&i.WeeklyReports,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTenantSettings = `-- name: CreateTenantSettings :one
INSERT INTO tenant_settings (
    tenant_id, company_name, company_logo_url, company_address,
    company_phone, company_email, timezone, currency_code,
    date_format, language, fiscal_year_start, tax_id, website_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
) RETURNING id, tenant_id, company_name, company_logo_url, company_address, company_phone, company_email, timezone, currency_code, date_format, language, fiscal_year_start, tax_id, website_url, created_at, updated_at
`

type CreateTenantSettingsParams struct {
	TenantID        uuid.UUID      `json:"tenant_id"`
	CompanyName     string         `json:"company_name"`
	CompanyLogoUrl  sql.NullString `json:"company_logo_url"`
	CompanyAddress  sql.NullString `json:"company_address"`
	CompanyPhone    sql.NullString `json:"company_phone"`
	CompanyEmail    sql.NullString `json:"company_email"`
	Timezone        sql.NullString `json:"timezone"`
	CurrencyCode    sql.NullString `json:"currency_code"`
	DateFormat      sql.NullString `json:"date_format"`
	Language        sql.NullString `json:"language"`
	FiscalYearStart sql.NullInt32  `json:"fiscal_year_start"`
	TaxID           sql.NullString `json:"tax_id"`
	WebsiteUrl      sql.NullString `json:"website_url"`
}

func (q *Queries) CreateTenantSettings(ctx context.Context, arg CreateTenantSettingsParams) (TenantSetting, error) {
	row := q.db.QueryRowContext(ctx, createTenantSettings,
		arg.TenantID,
		arg.CompanyName,
		arg.CompanyLogoUrl,
		arg.CompanyAddress,
		arg.CompanyPhone,
		arg.CompanyEmail,
		arg.Timezone,
		arg.CurrencyCode,
		arg.DateFormat,
		arg.Language,
		arg.FiscalYearStart,
		arg.TaxID,
		arg.WebsiteUrl,
	)
	var i TenantSetting
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyName,
		&i.CompanyLogoUrl,
		&i.CompanyAddress,
		&i.CompanyPhone,
		&i.CompanyEmail,
		&i.Timezone,
		&i.CurrencyCode,
		&i.DateFormat,
		&i.Language,
		&i.FiscalYearStart,
		&i.TaxID,
		&i.WebsiteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationSettings = `-- name: GetNotificationSettings :one
SELECT id, tenant_id, user_id, email_notifications, sms_notifications, push_notifications, low_stock_alerts, expiry_alerts, order_updates, payment_reminders, marketing_emails, weekly_reports, created_at, updated_at FROM notification_settings
WHERE tenant_id = $1 AND user_id = $2
`

type GetNotificationSettingsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) GetNotificationSettings(ctx context.Context, arg GetNotificationSettingsParams) (NotificationSetting, error) {
	row := q.db.QueryRowContext(ctx, getNotificationSettings, arg.TenantID, arg.UserID)
	var i NotificationSetting
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.EmailNotifications,
		&i.SmsNotifications,
		&i.PushNotifications,
		&i.LowStockAlerts,
		&i.ExpiryAlerts,
		&i.OrderUpdates,
		&i.PaymentReminders,
		&i.MarketingEmails,
		&i.WeeklyReports,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantSettings = `-- name: GetTenantSettings :one
SELECT id, tenant_id, company_name, company_logo_url, company_address, company_phone, company_email, timezone, currency_code, date_format, language, fiscal_year_start, tax_id, website_url, created_at, updated_at FROM tenant_settings
WHERE tenant_id = $1
`

func (q *Queries) GetTenantSettings(ctx context.Context, tenantID uuid.UUID) (TenantSetting, error) {
	row := q.db.QueryRowContext(ctx, getTenantSettings, tenantID)
	var i TenantSetting
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyName,
		&i.CompanyLogoUrl,
		&i.CompanyAddress,
		&i.CompanyPhone,
		&i.CompanyEmail,
		&i.Timezone,
		&i.CurrencyCode,
		&i.DateFormat,
		&i.Language,
		&i.FiscalYearStart,
		&i.TaxID,
		&i.WebsiteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotificationSettingsByTenant = `-- name: ListNotificationSettingsByTenant :many
SELECT id, tenant_id, user_id, email_notifications, sms_notifications, push_notifications, low_stock_alerts, expiry_alerts, order_updates, payment_reminders, marketing_emails, weekly_reports, created_at, updated_at FROM notification_settings
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationSettingsByTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListNotificationSettingsByTenant(ctx context.Context, arg ListNotificationSettingsByTenantParams) ([]NotificationSetting, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationSettingsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationSetting{}
	for rows.Next() {
		var i NotificationSetting
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.EmailNotifications,
			&i.SmsNotifications,
			&i.PushNotifications,
			&i.LowStockAlerts,
			&i.ExpiryAlerts,
			&i.OrderUpdates,
			&i.PaymentReminders,
			&i.MarketingEmails,
			&i.WeeklyReports,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationSettings = `-- name: UpdateNotificationSettings :one
UPDATE notification_settings
SET email_notifications = $3,
    sms_notifications = $4,
    push_notifications = $5,
    low_stock_alerts = $6,
    expiry_alerts = $7,
    order_updates = $8,
    payment_reminders = $9,
    marketing_emails = $10,
    weekly_reports = $11,
    updated_at = NOW()
WHERE tenant_id = $1 AND user_id = $2
RETURNING id, tenant_id, user_id, email_notifications, sms_notifications, push_notifications, low_stock_alerts, expiry_alerts, order_updates, payment_reminders, marketing_emails, weekly_reports, created_at, updated_at
`

type UpdateNotificationSettingsParams struct {
	TenantID           uuid.UUID    `json:"tenant_id"`
	UserID             uuid.UUID    `json:"user_id"`
	EmailNotifications sql.NullBool `json:"email_notifications"`
	SmsNotifications   sql.NullBool `json:"sms_notifications"`
	PushNotifications  sql.NullBool `json:"push_notifications"`
	LowStockAlerts     sql.NullBool `json:"low_stock_alerts"`
	ExpiryAlerts       sql.NullBool `json:"expiry_alerts"`
	OrderUpdates       sql.NullBool `json:"order_updates"`
	PaymentReminders   sql.NullBool `json:"payment_reminders"`
	MarketingEmails    sql.NullBool `json:"marketing_emails"`
	WeeklyReports      sql.NullBool `json:"weekly_reports"`
}

func (q *Queries) UpdateNotificationSettings(ctx context.Context, arg UpdateNotificationSettingsParams) (NotificationSetting, error) {
	row := q.db.QueryRowContext(ctx, updateNotificationSettings,
		arg.TenantID,
		arg.UserID,
		arg.EmailNotifications,
		arg.SmsNotifications,
		arg.PushNotifications,
		arg.LowStockAlerts,
		arg.ExpiryAlerts,
		arg.OrderUpdates,
		arg.PaymentReminders,
		arg.MarketingEmails,
		arg.WeeklyReports,
	)
	var i NotificationSetting
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.EmailNotifications,
		&i.SmsNotifications,
		&i.PushNotifications,
		&i.LowStockAlerts,
		&i.ExpiryAlerts,
		&i.OrderUpdates,
		&i.PaymentReminders,
		&i.MarketingEmails,
		&i.WeeklyReports,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenantSettings = `-- name: UpdateTenantSettings :one
UPDATE tenant_settings
SET company_name = $2,
    company_logo_url = $3,
    company_address = $4,
    company_phone = $5,
    company_email = $6,
    timezone = $7,
    currency_code = $8,
    date_format = $9,
    language = $10,
    fiscal_year_start = $11,
    tax_id = $12,
    website_url = $13,
    updated_at = NOW()
WHERE tenant_id = $1
RETURNING id, tenant_id, company_name, company_logo_url, company_address, company_phone, company_email, timezone, currency_code, date_format, language, fiscal_year_start, tax_id, website_url, created_at, updated_at
`

type UpdateTenantSettingsParams struct {
	TenantID        uuid.UUID      `json:"tenant_id"`
	CompanyName     string         `json:"company_name"`
	CompanyLogoUrl  sql.NullString `json:"company_logo_url"`
	CompanyAddress  sql.NullString `json:"company_address"`
	CompanyPhone    sql.NullString `json:"company_phone"`
	CompanyEmail    sql.NullString `json:"company_email"`
	Timezone        sql.NullString `json:"timezone"`
	CurrencyCode    sql.NullString `json:"currency_code"`
	DateFormat      sql.NullString `json:"date_format"`
	Language        sql.NullString `json:"language"`
	FiscalYearStart sql.NullInt32  `json:"fiscal_year_start"`
	TaxID           sql.NullString `json:"tax_id"`
	WebsiteUrl      sql.NullString `json:"website_url"`
}

func (q *Queries) UpdateTenantSettings(ctx context.Context, arg UpdateTenantSettingsParams) (TenantSetting, error) {
	row := q.db.QueryRowContext(ctx, updateTenantSettings,
		arg.TenantID,
		arg.CompanyName,
		arg.CompanyLogoUrl,
		arg.CompanyAddress,
		arg.CompanyPhone,
		arg.CompanyEmail,
		arg.Timezone,
		arg.CurrencyCode,
		arg.DateFormat,
		arg.Language,
		arg.FiscalYearStart,
		arg.TaxID,
		arg.WebsiteUrl,
	)
	var i TenantSetting
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyName,
		&i.CompanyLogoUrl,
		&i.CompanyAddress,
		&i.CompanyPhone,
		&i.CompanyEmail,
		&i.Timezone,
		&i.CurrencyCode,
		&i.DateFormat,
		&i.Language,
		&i.FiscalYearStart,
		&i.TaxID,
		&i.WebsiteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNotificationSettings = `-- name: UpsertNotificationSettings :one
INSERT INTO notification_settings (
    tenant_id, user_id, email_notifications, sms_notifications,
    push_notifications, low_stock_alerts, expiry_alerts,
    order_updates, payment_reminders, marketing_emails, weekly_reports
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (tenant_id, user_id)
DO UPDATE SET
    email_notifications = EXCLUDED.email_notifications,
    sms_notifications = EXCLUDED.sms_notifications,
    push_notifications = EXCLUDED.push_notifications,
    low_stock_alerts = EXCLUDED.low_stock_alerts,
    expiry_alerts = EXCLUDED.expiry_alerts,
    order_updates = EXCLUDED.order_updates,
    payment_reminders = EXCLUDED.payment_reminders,
    marketing_emails = EXCLUDED.marketing_emails,
    weekly_reports = EXCLUDED.weekly_reports,
    updated_at = NOW()
RETURNING id, tenant_id, user_id, email_notifications, sms_notifications, push_notifications, low_stock_alerts, expiry_alerts, order_updates, payment_reminders, marketing_emails, weekly_reports, created_at, updated_at
`

type UpsertNotificationSettingsParams struct {
	TenantID           uuid.UUID    `json:"tenant_id"`
	UserID             uuid.UUID    `json:"user_id"`
	EmailNotifications sql.NullBool `json:"email_notifications"`
	SmsNotifications   sql.NullBool `json:"sms_notifications"`
	PushNotifications  sql.NullBool `json:"push_notifications"`
	LowStockAlerts     sql.NullBool `json:"low_stock_alerts"`
	ExpiryAlerts       sql.NullBool `json:"expiry_alerts"`
	OrderUpdates       sql.NullBool `json:"order_updates"`
	PaymentReminders   sql.NullBool `json:"payment_reminders"`
	MarketingEmails    sql.NullBool `json:"marketing_emails"`
	WeeklyReports      sql.NullBool `json:"weekly_reports"`
}

func (q *Queries) UpsertNotificationSettings(ctx context.Context, arg UpsertNotificationSettingsParams) (NotificationSetting, error) {
	row := q.db.QueryRowContext(ctx, upsertNotificationSettings,
		arg.TenantID,
		arg.UserID,
		arg.EmailNotifications,
		arg.SmsNotifications,
		arg.PushNotifications,
		arg.LowStockAlerts,
		arg.ExpiryAlerts,
		arg.OrderUpdates,
		arg.PaymentReminders,
		arg.MarketingEmails,
		arg.WeeklyReports,
	)
	var i NotificationSetting
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.EmailNotifications,
		&i.SmsNotifications,
		&i.PushNotifications,
		&i.LowStockAlerts,
		&i.ExpiryAlerts,
		&i.OrderUpdates,
		&i.PaymentReminders,
		&i.MarketingEmails,
		&i.WeeklyReports,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTenantSettings = `-- name: UpsertTenantSettings :one
INSERT INTO tenant_settings (
    tenant_id, company_name, company_logo_url, company_address,
    company_phone, company_email, timezone, currency_code,
    date_format, language, fiscal_year_start, tax_id, website_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
ON CONFLICT (tenant_id)
DO UPDATE SET
    company_name = EXCLUDED.company_name,
    company_logo_url = EXCLUDED.company_logo_url,
    company_address = EXCLUDED.company_address,
    company_phone = EXCLUDED.company_phone,
    company_email = EXCLUDED.company_email,
    timezone = EXCLUDED.timezone,
    currency_code = EXCLUDED.currency_code,
    date_format = EXCLUDED.date_format,
    language = EXCLUDED.language,
    fiscal_year_start = EXCLUDED.fiscal_year_start,
    tax_id = EXCLUDED.tax_id,
    website_url = EXCLUDED.website_url,
    updated_at = NOW()
RETURNING id, tenant_id, company_name, company_logo_url, company_address, company_phone, company_email, timezone, currency_code, date_format, language, fiscal_year_start, tax_id, website_url, created_at, updated_at
`

type UpsertTenantSettingsParams struct {
	TenantID        uuid.UUID      `json:"tenant_id"`
	CompanyName     string         `json:"company_name"`
	CompanyLogoUrl  sql.NullString `json:"company_logo_url"`
	CompanyAddress  sql.NullString `json:"company_address"`
	CompanyPhone    sql.NullString `json:"company_phone"`
	CompanyEmail    sql.NullString `json:"company_email"`
	Timezone        sql.NullString `json:"timezone"`
	CurrencyCode    sql.NullString `json:"currency_code"`
	DateFormat      sql.NullString `json:"date_format"`
	Language        sql.NullString `json:"language"`
	FiscalYearStart sql.NullInt32  `json:"fiscal_year_start"`
	TaxID           sql.NullString `json:"tax_id"`
	WebsiteUrl      sql.NullString `json:"website_url"`
}

func (q *Queries) UpsertTenantSettings(ctx context.Context, arg UpsertTenantSettingsParams) (TenantSetting, error) {
	row := q.db.QueryRowContext(ctx, upsertTenantSettings,
		arg.TenantID,
		arg.CompanyName,
		arg.CompanyLogoUrl,
		arg.CompanyAddress,
		arg.CompanyPhone,
		arg.CompanyEmail,
		arg.Timezone,
		arg.CurrencyCode,
		arg.DateFormat,
		arg.Language,
		arg.FiscalYearStart,
		arg.TaxID,
		arg.WebsiteUrl,
	)
	var i TenantSetting
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CompanyName,
		&i.CompanyLogoUrl,
		&i.CompanyAddress,
		&i.CompanyPhone,
		&i.CompanyEmail,
		&i.Timezone,
		&i.CurrencyCode,
		&i.DateFormat,
		&i.Language,
		&i.FiscalYearStart,
		&i.TaxID,
		&i.WebsiteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
