// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password, phone, tenant_id, role)
VALUES ($1, $2, $3, $4, $5, CAST($6 AS user_role))
RETURNING id, name, email, password, phone, tenant_id, role::text AS role, email_verified, is_active, created_at
`

type CreateUserParams struct {
	Name     string      `json:"name"`
	Email    string      `json:"email"`
	Password string      `json:"password"`
	Phone    string      `json:"phone"`
	TenantID uuid.UUID   `json:"tenant_id"`
	Column6  interface{} `json:"column_6"`
}

type CreateUserRow struct {
	ID            uuid.UUID   `json:"id"`
	Name          string      `json:"name"`
	Email         string      `json:"email"`
	Password      string      `json:"password"`
	Phone         string      `json:"phone"`
	TenantID      uuid.UUID   `json:"tenant_id"`
	Role          string      `json:"role"`
	EmailVerified pgtype.Bool `json:"email_verified"`
	IsActive      pgtype.Bool `json:"is_active"`
	CreatedAt     time.Time   `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Phone,
		arg.TenantID,
		arg.Column6,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.TenantID,
		&i.Role,
		&i.EmailVerified,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password, phone, tenant_id, role::text AS role, email_verified, is_active, created_at FROM users
WHERE email = $1 AND tenant_id = $2
`

type GetUserByEmailParams struct {
	Email    string    `json:"email"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetUserByEmailRow struct {
	ID            uuid.UUID   `json:"id"`
	Name          string      `json:"name"`
	Email         string      `json:"email"`
	Password      string      `json:"password"`
	Phone         string      `json:"phone"`
	TenantID      uuid.UUID   `json:"tenant_id"`
	Role          string      `json:"role"`
	EmailVerified pgtype.Bool `json:"email_verified"`
	IsActive      pgtype.Bool `json:"is_active"`
	CreatedAt     time.Time   `json:"created_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.Email, arg.TenantID)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.TenantID,
		&i.Role,
		&i.EmailVerified,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmailAcrossTenants = `-- name: GetUserByEmailAcrossTenants :one
SELECT id, name, email, password, phone, tenant_id, role::text AS role, email_verified, is_active, created_at FROM users
WHERE email = $1
`

type GetUserByEmailAcrossTenantsRow struct {
	ID            uuid.UUID   `json:"id"`
	Name          string      `json:"name"`
	Email         string      `json:"email"`
	Password      string      `json:"password"`
	Phone         string      `json:"phone"`
	TenantID      uuid.UUID   `json:"tenant_id"`
	Role          string      `json:"role"`
	EmailVerified pgtype.Bool `json:"email_verified"`
	IsActive      pgtype.Bool `json:"is_active"`
	CreatedAt     time.Time   `json:"created_at"`
}

func (q *Queries) GetUserByEmailAcrossTenants(ctx context.Context, email string) (GetUserByEmailAcrossTenantsRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmailAcrossTenants, email)
	var i GetUserByEmailAcrossTenantsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.TenantID,
		&i.Role,
		&i.EmailVerified,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password, phone, tenant_id, role::text AS role, email_verified, is_active, created_at FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID            uuid.UUID   `json:"id"`
	Name          string      `json:"name"`
	Email         string      `json:"email"`
	Password      string      `json:"password"`
	Phone         string      `json:"phone"`
	TenantID      uuid.UUID   `json:"tenant_id"`
	Role          string      `json:"role"`
	EmailVerified pgtype.Bool `json:"email_verified"`
	IsActive      pgtype.Bool `json:"is_active"`
	CreatedAt     time.Time   `json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.TenantID,
		&i.Role,
		&i.EmailVerified,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listUsersByRole = `-- name: ListUsersByRole :many
SELECT id, name, email, password, phone, tenant_id, role::text AS role, email_verified, is_active, created_at FROM users
WHERE tenant_id = $1 AND role = CAST($2 AS user_role)
ORDER BY name
LIMIT $3 OFFSET $4
`

type ListUsersByRoleParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Column2  interface{} `json:"column_2"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type ListUsersByRoleRow struct {
	ID            uuid.UUID   `json:"id"`
	Name          string      `json:"name"`
	Email         string      `json:"email"`
	Password      string      `json:"password"`
	Phone         string      `json:"phone"`
	TenantID      uuid.UUID   `json:"tenant_id"`
	Role          string      `json:"role"`
	EmailVerified pgtype.Bool `json:"email_verified"`
	IsActive      pgtype.Bool `json:"is_active"`
	CreatedAt     time.Time   `json:"created_at"`
}

func (q *Queries) ListUsersByRole(ctx context.Context, arg ListUsersByRoleParams) ([]ListUsersByRoleRow, error) {
	rows, err := q.db.Query(ctx, listUsersByRole,
		arg.TenantID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersByRoleRow{}
	for rows.Next() {
		var i ListUsersByRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.Phone,
			&i.TenantID,
			&i.Role,
			&i.EmailVerified,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $2, email = $3, phone = $4, role = CAST($5 AS user_role), email_verified = $6
WHERE id = $1 AND tenant_id = $7
RETURNING id, name, email, password, phone, tenant_id, role::text AS role, email_verified, is_active, created_at
`

type UpdateUserParams struct {
	ID            uuid.UUID   `json:"id"`
	Name          string      `json:"name"`
	Email         string      `json:"email"`
	Phone         string      `json:"phone"`
	Column5       interface{} `json:"column_5"`
	EmailVerified pgtype.Bool `json:"email_verified"`
	TenantID      uuid.UUID   `json:"tenant_id"`
}

type UpdateUserRow struct {
	ID            uuid.UUID   `json:"id"`
	Name          string      `json:"name"`
	Email         string      `json:"email"`
	Password      string      `json:"password"`
	Phone         string      `json:"phone"`
	TenantID      uuid.UUID   `json:"tenant_id"`
	Role          string      `json:"role"`
	EmailVerified pgtype.Bool `json:"email_verified"`
	IsActive      pgtype.Bool `json:"is_active"`
	CreatedAt     time.Time   `json:"created_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Column5,
		arg.EmailVerified,
		arg.TenantID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.TenantID,
		&i.Role,
		&i.EmailVerified,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password = $1
WHERE id = $2 AND tenant_id = $3
`

type UpdateUserPasswordParams struct {
	Password string    `json:"password"`
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.Password, arg.ID, arg.TenantID)
	return err
}
